user_password_limit.settings:
  type: config_object
  label: 'Module Settings'
  mapping:
    limit_enable:
      type: boolean
      label: 'Enable Limit Reset Password'
    max_limit:
      type: integer
      label: 'Maximum Password Reset Count per day'